version: 2.1
jobs:
  deploy:
    resource_class: small
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - run:
        name: Install netlify cli
        command: sudo npm install netlify-cli -g
      - run:
        name: Yarn
        command: sudo yarn --frozen-lockfile
      - run:
        name: Build
        command: sudo yarn build
      - run:
        name: Deploy to Netlify
        command: sudo netlify deploy -p --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=out
workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]|[.])+/
