name: deploy
on:
  push:
    branches-ignore:
      - "*"
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build -p
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
